services:
  eshopdb:
    image: postgres

  distributed-cache:
    image: redis

  seq:
    image: datalust/seq:latest

  messagebus:
    image: rabbitmq:management

  identity:
    image: quay.io/keycloak/keycloak:26.1.2

volumes:
  postgres_eshopdb:
