services:
  eshopdb:
    container_name: eshopdb
    environment:
      - POSTGRES_DB=EshopDb
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    restart: on-failure
    ports:
      - "5432:5432"
    volumes:
      - postgres_eshopdb:/var/lib/postgresql/data

  distributed-cache:
    container_name: redis
    restart: on-failure
    ports:
      - "6379:6379"

  seq:
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    restart: on-failure
    ports:
      - "5341:5341"
      - "9091:80"

  messagebus:
    container_name: messagebus
    hostname: ecommerce-mq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    restart: on-failure
    ports:
      - "5672:5672"
      - "15672:15672"
