services:
  eshopdb:
    container_name: eshopdb
    environment:
      - POSTGRES_DB=EshopDb
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    restart: on-failure
    ports:
      - "5432:5432"
    volumes:
      - postgres_eshopdb:/var/lib/postgresql/data

  seq:
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    restart: on-failure
    ports:
      - "5341:5341"
      - "9091:80"
